# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@2
  inputs:
    command: 'version'
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure-connection-recom'
    runAzLogin: true
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'apply'
    environmentServiceName: 'Free Trial(ec88c61c-3230-434f-9bf2-a6eff5fe3e48)'
    runAzLogin: true
    allowTelemetryCollection: true



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
